[package]
name = "libratone-rs-ui"
version = "0.1.0"
authors = ["Adrien Bustany <adrien@bustany.org>"]
edition = "2021"

[lib]
name = "libratone_rs_ui"

[dependencies]
druid = { version = "0.7.0", features = ["im"] }
libratone-rs = { path = ".." }
